### ISSUE TITLE
Registering an external function

### ISSUE THREAD

**Issue by hedgar2017** [jazz-lang/JazzLight#2]
We would like to use your interpreter and language in our project called [torchbear](https://github.com/foundpatterns/torchbear), which is a developer accelerator.

The accelerator performs many kinds of helper actions:
- generating IDs, UUIDs, random strings etc.
- comparing and patching files just like `diff` and `patch` do
- many-many math functions
- [Full list](https://github.com/foundpatterns/torchbear#built-in-modules)

Those functions are coded in pure Rust and need to be called by user using bindings between a scripting language (that is, `Jazz`) and their implementation in Rust.

We have been using `Lua`, but now we are going to replace it with `Jazz`.
We could probably add the ability for registering external functions (along with existing `Jazz` built-ins) to make our bindings work. It will also allow you to code the `Jazz` standard library in high performance language like Rust.

Please, tell what you think. Thanks.

**Comment by naturallymitchell** [comment]
For example, [adding patch splitting](https://github.com/foundpatterns/torchbear/blob/6b82726b41426081775005aaa4a3b0a57bb841c4/src/bindings/text/splitdiff.rs) to the environment uses [add_method](https://docs.rs/rlua/0.16.2/rlua/?search=add_method) and [create_function](https://docs.rs/rlua/0.16.2/rlua/?search=create_function) through the [Lua programming language API](https://github.com/kyren/rlua).

**Comment by playXE** [comment]
I want to use `dlsym` on Linux to load external symbols and this is how it will look:
```coffeescript
extern function add(x,y) = load("std/file.rs"); // or .c file
```
Then if in "std" directory no compiled file call compiler of rust or c and emit shared library and then use `dlsym`

**Comment by playXE** [comment]
For now, I rewriting VM to allow multithreading and JIT compilation using [Jazz-jit](https://github.com/jazz-lang/Jazz-jit) for emitting X64 machine code.

**Comment by hedgar2017** [comment]
Cool. I think it should fit our needs on Linux.
@naturallymitchell is welcome to comment.

**Comment by playXE** [comment]
In new commit added `load` builtin.
Example of using:
```coffeescript
$load (string,string, int) -> function

var some_function = $load("path/to/dynlib/","funcname",1);

some_function(25)
```

**Comment by hedgar2017** [comment]
@playXE Please, add some Jazz code examples when you finish.

**Comment by playXE** [comment]
I encountered the problem with using `load` builtin, now I use `libloading` crate for load functions from dynamic libraries but when you try to call function loaded from the dynamic library program segfaults and I don't know why. 
The function may look like this:
```rust
#[no_mangle]
pub extern "C" fn test_func(_: &mut VM,_: Vec<P<Value>>) -> P<Value> {
    println!("Called function from dynamic library!");
    return P(Value::Null);
}
```
