### ISSUE TITLE
Finishing new VM implementation and compiler

### ISSUE THREAD

**Issue by playXE** [jazz-lang/JazzLight#3]
Roadmap for VM:
- [x] Multithreading without using `Arc` from std. Maybe implement garbage collector from scratch.
- [ ] x64 JIT Compiler
- [ ] TailCall implementation
- [x] Calls and object operations
- [x] Binary operations

Roadmap for compiler:
- [x] Function compilation
- [x] Handle global variables
- [ ] Try/Throw implementation
- [ ] Inline bytecode
      Example:
```
var a = 2
inline_bc(
"
AccInt 1
Push
AccStack <a>
Add 
"
)
```
- [x] Simple compilation.
For now code with simple arithmetic operations and variable initialization compiles
```
var a = 2 + 3 
var b = a + 2
return b
```
Compiles to this:
```
AccInt(2)
Push
AccInt(3)
Add
Push
AccStack0
Push
AccInt(2)
Add
Push
AccStack1
Ret(3)
Pop(2)
```

**Comment by playXE** [comment]
@hedgar2017 Maybe I will write VM in C or C++ and compiler in Rust or OCaml.  I want to write VM in C because I want to get maximum performance and small VM binary size. I still can use `Jazz-jit` since I got a C++ [binding](https://github.com/jazz-lang/Jazz-jit/blob/master/jazz-jit.hpp).

**Comment by hedgar2017** [comment]
@playXE Perfect.
By the way, which parts of your project are currently stabilized (e.g. Jazz syntax)? We would like to think how to integrate it into our project.

**Comment by playXE** [comment]
@hedgar2017 JazzLight syntax established now and VM with compiler will be established later

**Comment by playXE** [comment]
@hedgar2017 VM and compiler established. Next step is to write proper std and add some builtins to make language usable. Also added examples in `examples` folder
